# Generated by Django 3.0.5 on 2021-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, verbose_name='User')),
                ('name', models.CharField(max_length=120, verbose_name='İsim')),
                ('surname', models.CharField(max_length=120, verbose_name='Soyisim')),
                ('address', models.TextField(verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profili',
            },
        ),
    ]
